CREATE TABLE IF NOT EXISTS persisted_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    ingested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    payload CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_source ON persisted_record(source);
CREATE INDEX IF NOT EXISTS idx_type ON persisted_record(type);
CREATE INDEX IF NOT EXISTS idx_ingested_at ON persisted_record(ingested_at);